name: flutter_project_movie_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  platform_device_id: ^1.0.1
  device_info_plus: ^11.2.0
  android_id: ^0.2.0
  

dev_dependencies:
  flutter_native_splash: ^2.2.16

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/a.splash-screen.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/a.blankmovieposter.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-Medium.ttf

    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
